"""
E1 -- Rule-conformance invariant tests for BluffJAX's new games (Bluff, Kemps).

IMPORTANT: I (the assistant) could NOT run this file myself -- the sandbox I
worked in has no network access to install jax/flax and no GPU. This is written
by reading the actual environment source directly:
  bluffjax/environments/bluff/bluff.py
  bluffjax/environments/kemps/kemps.py
so the state field names, phase encoding, and API calls (env.reset, env.step,
env.get_avail_actions) are grounded in the real code, not guessed. But it has
NOT been executed against the real BluffJAX package -- run it in your normal
dev environment (wherever jax/flax are already installed) and fix any
mismatches before using results in a rebuttal response. Treat this as a strong
draft, not a finished, verified artifact.

Usage:
    cd bluffjax/bluffjax   # repo root containing the bluffjax package
    pytest /path/to/test_new_game_invariants.py -v

This directly addresses the AC's #1 priority: "make a test suite that verifies
that episodes generated by players adhere to the rules laid out somewhere" and
Reviewer 8LJg's question "How were the five new games validated for correctness
beyond running them? Is there any rule-conformance test...?"
"""

import jax
import jax.numpy as jnp
import pytest

from bluffjax import make


N_RANDOM_ROLLOUTS = 200
ROLLOUT_LEN = 150
SEED = 0


def _random_action(rng, avail):
    """Sample uniformly from legal actions given a boolean avail-action mask."""
    logits = jnp.where(avail, 0.0, -1e9)
    return jax.random.categorical(rng, logits)


# ---------------------------------------------------------------------------
# Bluff
# ---------------------------------------------------------------------------

class TestBluffInvariants:
    """
    Ground truth for these invariants comes directly from bluff.py:
    - BluffState.agent_hands: (num_agents, num_ranks) float counts per rank
    - BluffState.pile_hand: (num_ranks,) float counts per rank, cards in the
      central discard pile
    - reset() deals: agent_hands.sum() + pile_hand.sum() == deck_size always,
      since every card starts in exactly one of {a player's hand, the pile}
      and cards only ever move between agent_hands and pile_hand (do_play adds
      to pile_hand / removes from agent_hands; resolve_challenge adds pile
      back into the loser's hand and empties the pile). No card is ever
      created or destroyed by step_env.
    - agent_hand_sizes is maintained as agent_hands.sum(axis=1) at every
      state transition (see finish_play, resolve_challenge) -- should always
      be consistent, not just an independently-tracked counter that could
      drift from the real hand contents.
    """

    def _env(self, num_agents=3):
        return make("bluff", num_agents=num_agents, horizon=ROLLOUT_LEN)

    def _rollout(self, env, rng, max_steps=ROLLOUT_LEN):
        """Random-legal-action rollout, checking invariants at every step."""
        rng, reset_rng = jax.random.split(rng)
        state, obs = env.reset(reset_rng)
        deck_size = env.deck_size

        for t in range(max_steps):
            # --- invariant 1: card conservation ---
            total_cards = state.agent_hands.sum() + state.pile_hand.sum()
            assert jnp.isclose(total_cards, deck_size), (
                f"Card conservation violated at step {t}: "
                f"agent_hands.sum()={state.agent_hands.sum()} + "
                f"pile_hand.sum()={state.pile_hand.sum()} != deck_size={deck_size}"
            )

            # --- invariant 2: hand-size counter matches actual hand contents ---
            recomputed_sizes = state.agent_hands.sum(axis=1).astype(jnp.int32)
            assert jnp.array_equal(state.agent_hand_sizes, recomputed_sizes), (
                f"agent_hand_sizes drifted from agent_hands at step {t}: "
                f"tracked={state.agent_hand_sizes} recomputed={recomputed_sizes}"
            )

            # --- invariant 3: no negative card counts anywhere ---
            assert (state.agent_hands >= 0).all(), f"Negative hand count at step {t}"
            assert (state.pile_hand >= 0).all(), f"Negative pile count at step {t}"

            if bool(state.done):
                break

            # --- invariant 4: acting player always has >=1 legal action ---
            avail = env.get_avail_actions(state)
            assert avail.any(), (
                f"No legal actions available for the acting player at step {t}, "
                f"phase={state.phase} -- possible deadlock in game logic"
            )

            rng, act_rng, step_rng = jax.random.split(rng, 3)
            action = _random_action(act_rng, avail)
            state, obs, reward, absorbing, done, info = env.step(step_rng, state, action)

        return state

    def test_card_conservation_and_hand_size_consistency(self):
        env = self._env(num_agents=3)
        rng = jax.random.PRNGKey(SEED)
        for i in range(N_RANDOM_ROLLOUTS):
            rng, sub = jax.random.split(rng)
            self._rollout(env, sub)

    @pytest.mark.parametrize("num_agents", [2, 3, 4, 5])
    def test_card_conservation_various_player_counts(self, num_agents):
        env = self._env(num_agents=num_agents)
        rng = jax.random.PRNGKey(SEED + num_agents)
        for i in range(20):
            rng, sub = jax.random.split(rng)
            self._rollout(env, sub)

    def test_claim_size_never_exceeds_hand_or_cap(self):
        """Claimed size must be in [1,4] and the claimant must have had at
        least that many cards in hand at the moment of claiming (phase 0 ->
        1 transition). Checked via the claim_size field set in do_claim,
        which is min(action,3)+1, bounded correctly by construction in code
        -- this test exists to catch a *regression* if that logic changes."""
        env = self._env(num_agents=3)
        rng = jax.random.PRNGKey(SEED)
        rng, reset_rng = jax.random.split(rng)
        state, obs = env.reset(reset_rng)
        for t in range(ROLLOUT_LEN):
            if bool(state.done):
                break
            if int(state.phase) == 0:  # about to claim
                hand_size_before = int(
                    state.agent_hand_sizes[state.current_player_idx]
                )
            avail = env.get_avail_actions(state)
            assert avail.any()
            rng, act_rng, step_rng = jax.random.split(rng, 3)
            action = _random_action(act_rng, avail)
            state, obs, reward, absorbing, done, info = env.step(step_rng, state, action)
            if int(state.phase) == 1 and "claim_size" in info:
                assert 1 <= int(state.claim_size) <= 4
                assert int(state.claim_size) <= max(1, hand_size_before)


# ---------------------------------------------------------------------------
# Kemps
# ---------------------------------------------------------------------------

class TestKempsInvariants:
    """
    Ground truth from kemps.py:
    - KempsState.agent_hands: (num_agents, hand_size) card *indices* (0..deck_size-1)
    - KempsState.center_cards: (4,) card indices
    - KempsState.deck: remaining, undealt card indices, consumed via deck_idx
    - Every card index should appear in EXACTLY ONE of
      {agent_hands, center_cards, deck[deck_idx:]} at all times -- this is a
      much stronger check than a count-conservation check, because it also
      catches the swap logic (_process_swaps) accidentally duplicating or
      losing a specific card, which a pure count-based check could miss if a
      duplicate-for-duplicate swap happened to still sum correctly.
    - agent_hand_counts / center_counts (rank histograms) must always match
      the ranks implied by the actual card indices in agent_hands / center_cards.
    """

    def _env(self, num_agents=4):
        return make("kemps", num_agents=num_agents, horizon=ROLLOUT_LEN)

    def _check_no_duplicate_or_missing_cards(self, env, state, t):
        all_cards = jnp.concatenate(
            [
                state.agent_hands.reshape(-1),
                state.center_cards.reshape(-1),
                state.deck[state.deck_idx :],
            ]
        )
        deck_size = env.deck_size
        counts = jnp.bincount(all_cards, length=deck_size)
        assert jnp.all(counts == 1), (
            f"Card-uniqueness invariant violated at step {t}: "
            f"{int((counts == 0).sum())} cards missing, "
            f"{int((counts > 1).sum())} cards duplicated. "
            f"Expected every card index in [0,{deck_size}) to appear exactly once "
            f"across agent_hands + center_cards + remaining deck."
        )

    def _check_rank_counts_consistent(self, env, state, t):
        def ranks_of(cards):
            return cards // env.num_suits

        for agent in range(env.num_agents):
            recomputed = jnp.bincount(
                ranks_of(state.agent_hands[agent]),
                length=env.num_ranks,
                minlength=env.num_ranks,
            )
            assert jnp.array_equal(state.agent_hand_counts[agent], recomputed), (
                f"agent_hand_counts[{agent}] drifted from actual hand at step {t}"
            )
        recomputed_center = jnp.bincount(
            ranks_of(state.center_cards), length=env.num_ranks, minlength=env.num_ranks
        )
        assert jnp.array_equal(state.center_counts, recomputed_center), (
            f"center_counts drifted from actual center cards at step {t}"
        )

    def test_card_uniqueness_and_rank_counts(self):
        env = self._env(num_agents=4)
        rng = jax.random.PRNGKey(SEED)
        for i in range(N_RANDOM_ROLLOUTS):
            rng, reset_rng = jax.random.split(rng)
            state, obs = env.reset(reset_rng)
            for t in range(ROLLOUT_LEN):
                self._check_no_duplicate_or_missing_cards(env, state, t)
                self._check_rank_counts_consistent(env, state, t)
                if bool(state.done):
                    break
                avail = env.get_avail_actions(state)
                assert avail.all(axis=1).any() or avail.any(axis=1).all(), (
                    "Every agent should have >=1 legal action every step "
                    "(Kemps is simultaneous-move; noop is always legal)"
                )
                rng, act_rng, step_rng = jax.random.split(rng, 3)
                actions = jnp.stack(
                    [
                        _random_action(k, avail[a])
                        for a, k in enumerate(jax.random.split(act_rng, env.num_agents))
                    ]
                )
                state, obs, reward, absorbing, done, info = env.step(
                    step_rng, state, actions
                )

    def test_declare_rewards_are_zero_sum(self):
        """When a KEMPS/STOP KEMPS declaration resolves, reward is +/-1 per
        agent based on team membership (resolve_kemps / resolve_stop in
        kemps.py) -- by construction this should sum to exactly 0 across all
        4 agents every time a declaration fires. This is the single check
        that most directly demonstrates the game is well-posed as a
        zero-sum benchmark, addressing the AC's concern that correctness
        claims for the new games rest on self-consistency alone -- at least
        make that self-consistency check explicit and automated."""
        env = self._env(num_agents=4)
        rng = jax.random.PRNGKey(SEED)
        declare_events_checked = 0
        for i in range(N_RANDOM_ROLLOUTS):
            rng, reset_rng = jax.random.split(rng)
            state, obs = env.reset(reset_rng)
            for t in range(ROLLOUT_LEN):
                if bool(state.done):
                    break
                avail = env.get_avail_actions(state)
                rng, act_rng, step_rng = jax.random.split(rng, 3)
                # Bias toward declaring occasionally so this invariant actually
                # gets exercised rather than only ever hitting noop/swap.
                actions = jnp.stack(
                    [
                        _random_action(k, avail[a])
                        for a, k in enumerate(jax.random.split(act_rng, env.num_agents))
                    ]
                )
                state, obs, reward, absorbing, done, info = env.step(
                    step_rng, state, actions
                )
                if bool(done) and float(jnp.abs(reward).sum()) > 0:
                    assert jnp.isclose(reward.sum(), 0.0), (
                        f"Declaration reward not zero-sum: {reward} at step {t}"
                    )
                    declare_events_checked += 1
        assert declare_events_checked > 0, (
            "No KEMPS/STOP_KEMPS declarations were ever sampled under pure "
            "random play across all rollouts -- increase N_RANDOM_ROLLOUTS/"
            "ROLLOUT_LEN or bias the random policy toward declare actions, "
            "otherwise this test isn't actually exercising the invariant."
        )
