#loc = loc(unknown)
#loc1 = loc("leaves[0]")
#loc2 = loc("leaves[1]")
#loc3 = loc("leaves[2]")
#loc4 = loc("leaves[3]")
#loc5 = loc("leaves[4]")
#loc6 = loc("leaves[5]")
#loc7 = loc("leaves[6]")
#loc8 = loc("leaves[7]")
#loc9 = loc("leaves[8]")
#loc10 = loc("leaves[9]")
#loc11 = loc("leaves[10]")
#loc12 = loc("leaves[11]")
#loc13 = loc("leaves[12]")
#loc14 = loc("leaves[13]")
#loc24 = loc("scatter")
module @jit_avail attributes {jax.uses_shape_polymorphism = false, mhlo.num_partitions = 1 : i32, mhlo.num_replicas = 1 : i32} {
  func.func public @main(%arg0: tensor<52xi32> loc("leaves[0]"), %arg1: tensor<i32> loc("leaves[1]"), %arg2: tensor<2x7xi32> loc("leaves[2]"), %arg3: tensor<5xi1> loc("leaves[3]"), %arg4: tensor<2xf32> loc("leaves[4]"), %arg5: tensor<i32> loc("leaves[5]"), %arg6: tensor<i32> loc("leaves[6]"), %arg7: tensor<i32> loc("leaves[7]"), %arg8: tensor<5xi32> loc("leaves[8]"), %arg9: tensor<2xi1> loc("leaves[9]"), %arg10: tensor<i32> loc("leaves[10]"), %arg11: tensor<2xi1> loc("leaves[11]"), %arg12: tensor<i1> loc("leaves[12]"), %arg13: tensor<i32> loc("leaves[13]")) -> (tensor<4xi1> {jax.result_info = "result"}) {
    %0 = call @get_avail_actions(%arg0, %arg1, %arg2, %arg3, %arg4, %arg5, %arg6, %arg7, %arg8, %arg9, %arg10, %arg11, %arg12, %arg13) : (tensor<52xi32>, tensor<i32>, tensor<2x7xi32>, tensor<5xi1>, tensor<2xf32>, tensor<i32>, tensor<i32>, tensor<i32>, tensor<5xi32>, tensor<2xi1>, tensor<i32>, tensor<2xi1>, tensor<i1>, tensor<i32>) -> tensor<4xi1> loc(#loc15)
    return %0 : tensor<4xi1> loc(#loc)
  } loc(#loc)
  func.func private @get_avail_actions(%arg0: tensor<52xi32> loc(unknown), %arg1: tensor<i32> loc(unknown), %arg2: tensor<2x7xi32> loc(unknown), %arg3: tensor<5xi1> loc(unknown), %arg4: tensor<2xf32> loc(unknown), %arg5: tensor<i32> loc(unknown), %arg6: tensor<i32> loc(unknown), %arg7: tensor<i32> loc(unknown), %arg8: tensor<5xi32> loc(unknown), %arg9: tensor<2xi1> loc(unknown), %arg10: tensor<i32> loc(unknown), %arg11: tensor<2xi1> loc(unknown), %arg12: tensor<i1> loc(unknown), %arg13: tensor<i32> loc(unknown)) -> tensor<4xi1> {
    %c = stablehlo.constant dense<3> : tensor<i32> loc(#loc26)
    %c_0 = stablehlo.constant dense<1> : tensor<i32> loc(#loc26)
    %c_1 = stablehlo.constant dense<4> : tensor<i32> loc(#loc26)
    %c_2 = stablehlo.constant dense<5> : tensor<i32> loc(#loc26)
    %c_3 = stablehlo.constant dense<true> : tensor<i1> loc(#loc26)
    %cst = stablehlo.constant dense<0xFF800000> : tensor<f32> loc(#loc17)
    %c_4 = stablehlo.constant dense<2> : tensor<i32> loc(#loc26)
    %c_5 = stablehlo.constant dense<0> : tensor<i32> loc(#loc)
    %0 = stablehlo.compare  LT, %arg6, %c_5,  SIGNED : (tensor<i32>, tensor<i32>) -> tensor<i1> loc(#loc18)
    %1 = stablehlo.add %arg6, %c_4 : tensor<i32> loc(#loc19)
    %2 = stablehlo.select %0, %1, %arg6 : tensor<i1>, tensor<i32> loc(#loc20)
    %3 = stablehlo.dynamic_slice %arg4, %2, sizes = [1] : (tensor<2xf32>, tensor<i32>) -> tensor<1xf32> loc(#loc21)
    %4 = stablehlo.reshape %3 : (tensor<1xf32>) -> tensor<f32> loc(#loc22)
    %5 = stablehlo.reduce(%arg4 init: %cst) applies stablehlo.maximum across dimensions = [0] : (tensor<2xf32>, tensor<f32>) -> tensor<f32> loc(#loc17)
    %6 = stablehlo.broadcast_in_dim %c_3, dims = [] : (tensor<i1>) -> tensor<4xi1> loc(#loc23)
    %7 = stablehlo.compare  LT, %arg7, %c_5,  SIGNED : (tensor<i32>, tensor<i32>) -> tensor<i1> loc(#loc18)
    %8 = stablehlo.add %arg7, %c_2 : tensor<i32> loc(#loc19)
    %9 = stablehlo.select %7, %8, %arg7 : tensor<i1>, tensor<i32> loc(#loc20)
    %10 = stablehlo.dynamic_slice %arg8, %9, sizes = [1] : (tensor<5xi32>, tensor<i32>) -> tensor<1xi32> loc(#loc21)
    %11 = stablehlo.reshape %10 : (tensor<1xi32>) -> tensor<i32> loc(#loc22)
    %12 = stablehlo.compare  LT, %11, %c_1,  SIGNED : (tensor<i32>, tensor<i32>) -> tensor<i1> loc(#loc18)
    %13 = stablehlo.broadcast_in_dim %c_0, dims = [] : (tensor<i32>) -> tensor<1xi32> loc(#loc23)
    %14 = "stablehlo.scatter"(%6, %13, %12) <{indices_are_sorted = true, scatter_dimension_numbers = #stablehlo.scatter<inserted_window_dims = [0], scatter_dims_to_operand_dims = [0]>, unique_indices = true}> ({
    ^bb0(%arg14: tensor<i1> loc("scatter"), %arg15: tensor<i1> loc("scatter")):
      stablehlo.return %arg15 : tensor<i1> loc(#loc24)
    }) : (tensor<4xi1>, tensor<1xi32>, tensor<i1>) -> tensor<4xi1> loc(#loc24)
    %15 = stablehlo.compare  LT, %4, %5,  FLOAT : (tensor<f32>, tensor<f32>) -> tensor<i1> loc(#loc18)
    %16 = stablehlo.broadcast_in_dim %c_5, dims = [] : (tensor<i32>) -> tensor<1xi32> loc(#loc23)
    %17 = "stablehlo.scatter"(%14, %16, %15) <{indices_are_sorted = true, scatter_dimension_numbers = #stablehlo.scatter<inserted_window_dims = [0], scatter_dims_to_operand_dims = [0]>, unique_indices = true}> ({
    ^bb0(%arg14: tensor<i1> loc("scatter"), %arg15: tensor<i1> loc("scatter")):
      stablehlo.return %arg15 : tensor<i1> loc(#loc24)
    }) : (tensor<4xi1>, tensor<1xi32>, tensor<i1>) -> tensor<4xi1> loc(#loc24)
    %18 = stablehlo.compare  EQ, %4, %5,  FLOAT : (tensor<f32>, tensor<f32>) -> tensor<i1> loc(#loc25)
    %19 = stablehlo.broadcast_in_dim %c, dims = [] : (tensor<i32>) -> tensor<1xi32> loc(#loc23)
    %20 = "stablehlo.scatter"(%17, %19, %18) <{indices_are_sorted = true, scatter_dimension_numbers = #stablehlo.scatter<inserted_window_dims = [0], scatter_dims_to_operand_dims = [0]>, unique_indices = true}> ({
    ^bb0(%arg14: tensor<i1> loc("scatter"), %arg15: tensor<i1> loc("scatter")):
      stablehlo.return %arg15 : tensor<i1> loc(#loc24)
    }) : (tensor<4xi1>, tensor<1xi32>, tensor<i1>) -> tensor<4xi1> loc(#loc24)
    return %20 : tensor<4xi1> loc(#loc26)
  } loc(#loc26)
} loc(#loc)
#loc15 = loc("jit(avail)/jit(get_avail_actions)")
#loc16 = loc("jit(avail)/jit")
#loc17 = loc("reduce_max")
#loc18 = loc("lt")
#loc19 = loc("add")
#loc20 = loc("select_n")
#loc21 = loc("dynamic_slice")
#loc22 = loc("squeeze")
#loc23 = loc("broadcast_in_dim")
#loc25 = loc("eq")
#loc26 = loc("jit:"(#loc16))
