#loc = loc(unknown)
#loc1 = loc("leaves[0]")
#loc2 = loc("leaves[1]")
#loc3 = loc("leaves[2]")
#loc4 = loc("leaves[3]")
#loc5 = loc("leaves[4]")
#loc6 = loc("leaves[5]")
#loc7 = loc("leaves[6]")
#loc8 = loc("leaves[7]")
#loc9 = loc("leaves[8]")
#loc10 = loc("leaves[9]")
#loc11 = loc("leaves[10]")
#loc12 = loc("leaves[11]")
#loc13 = loc("leaves[12]")
#loc14 = loc("leaves[13]")
#loc15 = loc("leaves[14]")
#loc16 = loc("leaves[15]")
#loc26 = loc("scatter")
module @jit_avail attributes {jax.uses_shape_polymorphism = false, mhlo.num_partitions = 1 : i32, mhlo.num_replicas = 1 : i32} {
  func.func public @main(%arg0: tensor<2xi32> loc("leaves[0]"), %arg1: tensor<i32> loc("leaves[1]"), %arg2: tensor<6xi32> loc("leaves[2]"), %arg3: tensor<2xf32> loc("leaves[3]"), %arg4: tensor<f32> loc("leaves[4]"), %arg5: tensor<i32> loc("leaves[5]"), %arg6: tensor<i32> loc("leaves[6]"), %arg7: tensor<i32> loc("leaves[7]"), %arg8: tensor<2xi1> loc("leaves[8]"), %arg9: tensor<i32> loc("leaves[9]"), %arg10: tensor<i32> loc("leaves[10]"), %arg11: tensor<2x4xi32> loc("leaves[11]"), %arg12: tensor<i32> loc("leaves[12]"), %arg13: tensor<2xi1> loc("leaves[13]"), %arg14: tensor<i1> loc("leaves[14]"), %arg15: tensor<i32> loc("leaves[15]")) -> (tensor<3xi1> {jax.result_info = "result"}) {
    %0 = call @get_avail_actions(%arg0, %arg1, %arg2, %arg3, %arg4, %arg5, %arg6, %arg7, %arg8, %arg9, %arg10, %arg11, %arg12, %arg13, %arg14, %arg15) : (tensor<2xi32>, tensor<i32>, tensor<6xi32>, tensor<2xf32>, tensor<f32>, tensor<i32>, tensor<i32>, tensor<i32>, tensor<2xi1>, tensor<i32>, tensor<i32>, tensor<2x4xi32>, tensor<i32>, tensor<2xi1>, tensor<i1>, tensor<i32>) -> tensor<3xi1> loc(#loc17)
    return %0 : tensor<3xi1> loc(#loc)
  } loc(#loc)
  func.func private @get_avail_actions(%arg0: tensor<2xi32> loc(unknown), %arg1: tensor<i32> loc(unknown), %arg2: tensor<6xi32> loc(unknown), %arg3: tensor<2xf32> loc(unknown), %arg4: tensor<f32> loc(unknown), %arg5: tensor<i32> loc(unknown), %arg6: tensor<i32> loc(unknown), %arg7: tensor<i32> loc(unknown), %arg8: tensor<2xi1> loc(unknown), %arg9: tensor<i32> loc(unknown), %arg10: tensor<i32> loc(unknown), %arg11: tensor<2x4xi32> loc(unknown), %arg12: tensor<i32> loc(unknown), %arg13: tensor<2xi1> loc(unknown), %arg14: tensor<i1> loc(unknown), %arg15: tensor<i32> loc(unknown)) -> tensor<3xi1> {
    %c = stablehlo.constant dense<true> : tensor<i1> loc(#loc29)
    %c_0 = stablehlo.constant dense<1> : tensor<i32> loc(#loc29)
    %c_1 = stablehlo.constant dense<false> : tensor<i1> loc(#loc29)
    %c_2 = stablehlo.constant dense<2> : tensor<i32> loc(#loc)
    %c_3 = stablehlo.constant dense<0> : tensor<i32> loc(#loc)
    %0 = stablehlo.compare  LT, %arg10, %c_3,  SIGNED : (tensor<i32>, tensor<i32>) -> tensor<i1> loc(#loc19)
    %1 = stablehlo.add %arg10, %c_2 : tensor<i32> loc(#loc20)
    %2 = stablehlo.select %0, %1, %arg10 : tensor<i1>, tensor<i32> loc(#loc21)
    %3 = stablehlo.dynamic_slice %arg3, %2, sizes = [1] : (tensor<2xf32>, tensor<i32>) -> tensor<1xf32> loc(#loc22)
    %4 = stablehlo.reshape %3 : (tensor<1xf32>) -> tensor<f32> loc(#loc23)
    %5 = stablehlo.broadcast_in_dim %c_1, dims = [] : (tensor<i1>) -> tensor<3xi1> loc(#loc24)
    %6 = stablehlo.compare  GT, %arg4, %4,  FLOAT : (tensor<f32>, tensor<f32>) -> tensor<i1> loc(#loc25)
    %7 = stablehlo.broadcast_in_dim %c_3, dims = [] : (tensor<i32>) -> tensor<1xi32> loc(#loc24)
    %8 = "stablehlo.scatter"(%5, %7, %6) <{indices_are_sorted = true, scatter_dimension_numbers = #stablehlo.scatter<inserted_window_dims = [0], scatter_dims_to_operand_dims = [0]>, unique_indices = true}> ({
    ^bb0(%arg16: tensor<i1> loc("scatter"), %arg17: tensor<i1> loc("scatter")):
      stablehlo.return %arg17 : tensor<i1> loc(#loc26)
    }) : (tensor<3xi1>, tensor<1xi32>, tensor<i1>) -> tensor<3xi1> loc(#loc26)
    %9 = stablehlo.broadcast_in_dim %c_0, dims = [] : (tensor<i32>) -> tensor<1xi32> loc(#loc24)
    %10 = "stablehlo.scatter"(%8, %9, %c) <{indices_are_sorted = true, scatter_dimension_numbers = #stablehlo.scatter<inserted_window_dims = [0], scatter_dims_to_operand_dims = [0]>, unique_indices = true}> ({
    ^bb0(%arg16: tensor<i1> loc("scatter"), %arg17: tensor<i1> loc("scatter")):
      stablehlo.return %arg17 : tensor<i1> loc(#loc26)
    }) : (tensor<3xi1>, tensor<1xi32>, tensor<i1>) -> tensor<3xi1> loc(#loc26)
    %11 = stablehlo.compare  LT, %arg7, %c_2,  SIGNED : (tensor<i32>, tensor<i32>) -> tensor<i1> loc(#loc19)
    %12 = stablehlo.broadcast_in_dim %c_2, dims = [] : (tensor<i32>) -> tensor<1xi32> loc(#loc24)
    %13 = "stablehlo.scatter"(%10, %12, %11) <{indices_are_sorted = true, scatter_dimension_numbers = #stablehlo.scatter<inserted_window_dims = [0], scatter_dims_to_operand_dims = [0]>, unique_indices = true}> ({
    ^bb0(%arg16: tensor<i1> loc("scatter"), %arg17: tensor<i1> loc("scatter")):
      stablehlo.return %arg17 : tensor<i1> loc(#loc26)
    }) : (tensor<3xi1>, tensor<1xi32>, tensor<i1>) -> tensor<3xi1> loc(#loc26)
    %14 = stablehlo.not %arg14 : tensor<i1> loc(#loc27)
    %15 = stablehlo.broadcast_in_dim %14, dims = [] : (tensor<i1>) -> tensor<3xi1> loc(#loc28)
    %16 = stablehlo.and %13, %15 : tensor<3xi1> loc(#loc28)
    return %16 : tensor<3xi1> loc(#loc29)
  } loc(#loc29)
} loc(#loc)
#loc17 = loc("jit(avail)/jit(get_avail_actions)")
#loc18 = loc("jit(avail)/jit")
#loc19 = loc("lt")
#loc20 = loc("add")
#loc21 = loc("select_n")
#loc22 = loc("dynamic_slice")
#loc23 = loc("squeeze")
#loc24 = loc("broadcast_in_dim")
#loc25 = loc("gt")
#loc27 = loc("not")
#loc28 = loc("and")
#loc29 = loc("jit:"(#loc18))
